### ISSUE TITLE
Confused about routing - urls not defined yet...

### ISSUE THREAD

**Issue by acroyear** [michijs/michijs#171]
In your code example you have <Redirect> defined as using goTo (part of the dist) and urls.

But urls isn't defined yet, as that happens in the next section of registerRoutes that, well, uses <Redirect>, meaning there's a circular loop.

Any way you could clear that up?

---

My use-case. A basic music player (artists, then albums, or folders then contents, playlists), which is controlled by path including id's "/album/<id>" or "/artist/<id1>/album<id2>"

Then I want to use searchParams for 2 overlay states, dialog and player.

dialog=<dialog component>, so if dialog is showing, that shows up on top of whatever component is being rendered at the time (e.g., a drawer for changing to a different page, or the dialog for logging in or changing server). Another dialog might be the current play queue. The idea of the query-param routes is to be able to support mobile back-button which is expected behavior on Android devices.

The player= boolean would overlay the player controls on top of whatever was there. they could close the player controls to surf around to pick something else to play - changing the main route but at any time they could click to pop the player controls back on top.

**Comment by lsegurado** [comment]
You're right, I ran into the same issue a couple of weeks ago and fixed it in version 2.0 (still in progress). But I will upload a patch in the next few minutes for version 1.0. The solution is simple: Link can receive a function as a url; That is, this code is valid:
`<Link url={() => urls.yourRoute()}>Go to your route</Link>`

**Comment by lsegurado** [comment]
Fixed on [1.1.8](https://github.com/michijs/michijs/releases/tag/v1.1.8)
